from . import ExifTags as ExifTags,ImagePalette as ImagePalette
from _typeshed import Incomplete
from .Image import Image

def autocontrast(image: Image, cutoff: int | tuple[int,int] = ..., ignore: Incomplete | None = ..., mask: Incomplete | None = ..., preserve_tone: bool = ...) -> Image: ...
def colorize(image, black, white, mid: Incomplete | None = ..., blackpoint: int = ..., whitepoint: int = ..., midpoint: int = ...): ...
def contain(image, size, method=...): ...
def pad(image, size, method=..., color: Incomplete | None = ..., centering=...): ...
def crop(image, border: int = ...): ...
def scale(image, factor, resample=...): ...
def deform(image, deformer, resample=...): ...
def equalize(image, mask: Incomplete | None = ...): ...
def expand(image, border: int = ..., fill: int = ...): ...
def fit(image, size, method=..., bleed: float = ..., centering=...): ...
def flip(image): ...
def grayscale(image): ...
def invert(image): ...
def mirror(image): ...
def posterize(image, bits): ...
def solarize(image, threshold: int = ...): ...
def exif_transpose(image, *, in_place: bool = ...): ...
