from _typeshed import Incomplete
import luma.core.mixin as mixin

class device(mixin.capabilities):
    def __init__(self, const: Incomplete | None = ..., serial_interface: Incomplete | None = ...) -> None: ...
    def command(self, *cmd: Incomplete) -> None: ...
    def data(self, data: Incomplete) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def contrast(self, leve: Incomplete) -> None: ...
    def cleanup(self) -> None: ...

