import numpy as np
from .configuration import CameraConfiguration as CameraConfiguration
from .controls import Controls as Controls
from .job import Job as Job
from .request import CompletedRequest as CompletedRequest, Helpers as Helpers
from .sensor_format import SensorFormat as SensorFormat
from PIL.Image import Image
from _typeshed import Incomplete
from enum import Enum
from picamera2.encoders import Encoder as Encoder, H264Encoder as H264Encoder, MJPEGEncoder as MJPEGEncoder, Quality as Quality
from picamera2.outputs import FfmpegOutput as FfmpegOutput, FileOutput as FileOutput
from picamera2.previews import DrmPreview as DrmPreview, NullPreview as NullPreview, QtGlPreview as QtGlPreview, QtPreview as QtPreview
from typing import Any, Dict, List, Tuple

STILL: Incomplete
RAW: Incomplete
VIDEO: Incomplete
VIEWFINDER: Incomplete

class Preview(Enum):
    NULL: int
    DRM: int
    QT: int
    QTGL: int

class CameraManager:
    running: bool
    cameras: Incomplete
    def __init__(self) -> None: ...
    cms: Incomplete
    thread: Incomplete
    def setup(self) -> None: ...
    def add(self, index, camera) -> None: ...
    def cleanup(self, index) -> None: ...
    def listen(self) -> None: ...
    def handle_request(self, flushid: Incomplete | None = ...) -> None: ...

class Picamera2:
    DEBUG: Incomplete
    INFO: Incomplete
    WARNING: Incomplete
    ERROR: Incomplete
    CRITICAL: Incomplete
    @staticmethod
    def set_logging(level=..., output=..., msg: Incomplete | None = ...) -> None: ...
    @staticmethod
    def load_tuning_file(tuning_file, dir: Incomplete | None = ...): ...
    @staticmethod
    def find_tuning_algo(tuning: dict, name: str) -> dict: ...
    @staticmethod
    def global_camera_info() -> list: ...
    notifymeread: Incomplete
    camera_idx: Incomplete
    verbose_console: Incomplete
    helpers: Incomplete
    def __init__(self, camera_num: int = ..., verbose_console: Incomplete | None = ..., tuning: Incomplete | None = ...) -> None: ...
    @property
    def camera_manager(self): ...
    @property
    def preview_configuration(self) -> CameraConfiguration: ...
    @property
    def still_configuration(self) -> CameraConfiguration: ...
    @property
    def video_configuration(self) -> CameraConfiguration: ...
    @property
    def request_callback(self): ...
    @property
    def camera_properties(self) -> dict: ...
    @property
    def camera_controls(self) -> dict: ...
    @property
    def title_fields(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_traceback) -> None: ...
    def __del__(self) -> None: ...
    sensor_modes_: Incomplete
    @property
    def sensor_modes(self) -> list: ...
    def attach_preview(self, preview) -> None: ...
    def start_preview(self, preview: bool = ..., **kwargs) -> None: ...
    def detach_preview(self) -> None: ...
    def stop_preview(self) -> None: ...
    is_open: bool
    streams: Incomplete
    stream_map: Incomplete
    camera: Incomplete
    camera_ctrl_info: Incomplete
    camera_config: Incomplete
    libcamera_config: Incomplete
    preview_configuration_: Incomplete
    still_configuration_: Incomplete
    video_configuration_: Incomplete
    allocator: Incomplete
    def close(self) -> None: ...
    def create_preview_configuration(self, main:dict[str, Any]=..., lores: Incomplete | None = ..., raw=..., transform=..., colour_space=..., buffer_count: int = ..., controls=..., display: str = ..., encode: str = ..., queue: bool = ...) -> dict[str,Any]: ...
    def create_still_configuration(self, main: dict[str, Any]=..., lores: Incomplete | None = ..., raw=..., transform=..., colour_space=..., buffer_count: int = ..., controls=..., display: Incomplete | None = ..., encode: Incomplete | None = ..., queue: bool = ...) -> dict[str,Any]: ...
    def create_video_configuration(self, main=..., lores: Incomplete | None = ..., raw=..., transform=..., colour_space: Incomplete | None = ..., buffer_count: int = ..., controls=..., display: str = ..., encode: str = ..., queue: bool = ...) -> dict[str,Any]: ...
    def check_stream_config(self, stream_config, name) -> None: ...
    def check_camera_config(self, camera_config: dict) -> None: ...
    @staticmethod
    def align_stream(stream_config: dict, optimal: bool = ...) -> None: ...
    @staticmethod
    def align_configuration(config: dict, optimal: bool = ...) -> None: ...
    camera_properties_: Incomplete
    display_stream_name: Incomplete
    encode_stream_name: Incomplete
    controls: Incomplete
    def configure_(self, camera_config: str = ...) -> None: ...
    def configure(self, camera_config: str | dict[str,Any] = ...) -> None: ...
    def camera_configuration(self) -> dict: ...
    def stream_configuration(self, name: str = ...) -> dict: ...
    started: bool
    def start_(self) -> None: ...
    def start(self, config: Incomplete | None = ..., show_preview: bool = ...) -> None: ...
    completed_requests: Incomplete
    def stop_(self, request: Incomplete | None = ...) -> None: ...
    def stop(self) -> None: ...
    def set_controls(self, controls: dict[str, Any]) -> None: ...
    def process_requests(self, display) -> None: ...
    def wait(self, job): ...
    def dispatch_functions(self, functions, wait, signal_function: Incomplete | None = ..., immediate: bool = ...) -> None: ...
    def capture_file_(self, file_output, name: str, format: Incomplete | None = ...) -> dict: ...
    def capture_file(self, file_output: str, name: str = ..., format: Incomplete | None = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...) -> Incomplete: ...
    def switch_mode_(self, camera_config): ...
    def switch_mode(self, camera_config, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_file(self, camera_config, file_output, name: str = ..., format: Incomplete | None = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_request(self, camera_config, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_request_(self): ...
    def capture_request(self, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_capture_request_and_stop(self, camera_config, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_metadata_(self): ...
    def capture_metadata(self, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_buffer_(self, name): ...
    def capture_buffer(self, name: str = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_buffers_and_metadata_(self, names) -> Tuple[List[np.ndarray], dict]: ...
    def capture_buffers(self, names=..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_buffer(self, camera_config, name: str = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_buffers(self, camera_config, names=..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_array_(self, name): ...
    def capture_array(self, name: str = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_arrays_and_metadata_(self, names) -> Tuple[List[np.ndarray], Dict[str, Any]]: ...
    def capture_arrays(self, names=..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_array(self, camera_config, name: str = ..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def switch_mode_and_capture_arrays(self, camera_config, names=..., wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
    def capture_image_(self, name: str) -> Image: ...
    def capture_image(self, name: str = ..., wait: bool = ..., signal_function: Incomplete | None = ...) -> Image: ...
    def switch_mode_and_capture_image(self, camera_config, name: str = ..., wait: bool = ..., signal_function: Incomplete | None = ...) -> Image: ...
    def start_encoder(self, encoder: Incomplete | None = ..., output: Incomplete | None = ..., pts: Incomplete | None = ..., quality: Incomplete | None = ..., name: Incomplete | None = ...) -> None: ...
    def stop_encoder(self, encoders: Incomplete | None = ...) -> None: ...
    @property
    def encoders(self) -> set[Encoder]: ...
    def start_recording(self, encoder, output, pts: Incomplete | None = ..., config: Incomplete | None = ..., quality: Incomplete | None = ..., name: Incomplete | None = ...) -> None: ...
    def stop_recording(self) -> None: ...
    def set_overlay(self, overlay) -> None: ...
    def start_and_capture_files(self, name: str = ..., initial_delay: int = ..., preview_mode: str = ..., capture_mode: str = ..., num_files: int = ..., delay: int = ..., show_preview: bool = ...): ...
    def start_and_capture_file(self, name: str = ..., delay: int = ..., preview_mode: str = ..., capture_mode: str = ..., show_preview: bool = ...) -> None: ...
    def start_and_record_video(self, output, encoder: Incomplete | None = ..., config: Incomplete | None = ..., quality=..., show_preview: bool = ..., duration: int = ..., audio: bool = ...) -> None: ...
    def autofocus_cycle(self, wait: Incomplete | None = ..., signal_function: Incomplete | None = ...): ...
